INSERT INTO `permissons` (`name`, `category`, `created_at`, `updated_at`) VALUES
('Candidate Registration', 'form', NULL, NULL),
('Candidate Educational Assessment', 'form', NULL, NULL),
('Candidate CRS calculator', 'form', NULL, NULL),
('Candidate InProgress Report', 'form', NULL, NULL),
('Institution registration form', 'form', NULL, NULL),
('Institution InProgress Report', 'form', NULL, NULL),
('RCIC Consultant registration form', 'form', NULL, NULL),
('RCIC Consultant InProgress Report', 'form', NULL, NULL),
('Immigration registration form', 'form', NULL, NULL),
('Immigration InProgress Report', 'form', NULL, NULL),
('Chartered registration form', 'form', NULL, NULL),
('Chartered InProgress Report', 'form', NULL, NULL),
('Candidate enquiry view status', 'enquiry', NULL, NULL),
('Institution enquiry view status', 'enquiry', NULL, NULL),
('RCIC Consultant enquiry view status', 'enquiry', NULL, NULL),
('Immigration enquiry view status', 'enquiry', NULL, NULL),
('Chartered Accountant enquiry view status', 'enquiry', NULL, NULL),
('Candidate enquiry forward', 'enquiry', NULL, NULL),
('Institution enquiry forward', 'enquiry', NULL, NULL),
('RCIC Consultant enquiry forward\r\n', 'enquiry', NULL, NULL),
('Immigration enquiry forward', 'enquiry', NULL, NULL),
('Chartered Accountant enquiry forward', 'enquiry', NULL, NULL),
('Add', 'User managing', NULL, NULL),
('Edit', 'User managing', NULL, NULL),
('Suspend', 'User managing', NULL, NULL),
('Reset Password', 'User managing', NULL, NULL),
('view', 'User managing', NULL, NULL),
('Accounting', 'Reports', NULL, NULL),
('membership expiry', 'Reports', NULL, NULL),
('Enquiries', 'Reports', NULL, NULL),
('Dashboard', 'others', NULL, NULL),
('Account', 'others', NULL, NULL),
('Settings', 'others', NULL, NULL);